- name: delete K8s_manifest/rook-1.4.1/filesystem.yaml
  run_once: true
  shell: "kubectl delete -f K8s_manifest/rook-1.4.1/filesystem.yaml"
  when: ceph_type=="cephfs"

- name: delete K8s_manifest/rook-1.4.1/csi/{{ ceph_type }}/storageclass.yaml
  run_once: true
  shell: "kubectl delete -f K8s_manifest/rook-1.4.1/csi/{{ ceph_type }}/storageclass.yaml"

- name: delete K8s_manifest/rook-1.4.1/toolbox.yaml
  run_once: true
  shell: "kubectl delete -f K8s_manifest/rook-1.4.1/toolbox.yaml"

- name: delete K8s_manifest/rook-1.4.1/cluster-on-pvc.yaml
  run_once: true
  shell: "kubectl delete -f K8s_manifest/rook-1.4.1/cluster-on-pvc.yaml"

- name: delete K8s_manifest/rook-1.4.1/operator.yaml
  run_once: true
  shell: "kubectl delete -f K8s_manifest/rook-1.4.1/operator.yaml"

- name: deploy K8s_manifest/rook-1.4.1/common.yaml
  run_once: true
  shell: "kubectl apply -f K8s_manifest/rook-1.4.1/common.yaml"
  