- name: apt uninstall lvm2
  become: true
  apt:
    state: absent
    purge: true
    autoremove: true
    name: lvm2

- name: delete /var/lib/rook
  become: true
  file:
    state: absent
    path: "/var/lib/rook"