---
- import_tasks: "uninstall_K8s_pkgmanager.yaml"
  when: "'controlPlaneNodes' in group_names"
- import_tasks: "docker.yaml"
- import_tasks: "apt.yaml"
- import_tasks: "ufw.yaml"
- import_tasks: "reboot.yaml"