- name: kubeadm reset
  become: true
  shell: "kubeadm reset -f"
   
- name: waiting for stop kubelet.service
  become: true
  shell: |
    STATUS="bad"
    SYSTEMD=`systemctl status kubelet.service | grep Active | sed "s/\ /\n/g" \
                                                    | sed "/^$/d" | grep active`
    if [ -z "`$SYSTEMD`" ];then
      STATUS="ok"
    fi

    echo $STATUS
  register: kubelet_status
  retries: 50
  delay: 5
  until: "kubelet_status.stdout_lines[0]=='ok'"

- name: delete /etc/kubernetes
  become: true
  file:
    path: "/etc/kubernetes"
    state: absent