- name: helm install repository  "jetstack https://charts.jetstack.io"
  run_once: true
  shell: |
    helm repo add jetstack https://charts.jetstack.io
    kubectl create namespace cert-manager
    helm install cert-manager --namespace cert-manager jetstack/cert-manager \
      --values $HOME/K8s_manifest/certmanager/values.yaml --version v0.15.1

- name: waiting for complete 'helm install cert-manager'
  run_once: true
  shell: "helm status -n cert-manager cert-manager | grep STATUS"
  register: certmanager_status
  retries: 100
  delay: 3
  until: "certmanager_status.stdout_lines[0]=='STATUS: deployed'"

- name: waiting for start cert-manager pod...
  run_once: true
  shell: |
    STATUS="bad"
    NAME_SPACE="cert-manager"
    POD_LABEL="app.kubernetes.io/instance=cert-manager"
    POD_NAME=`kubectl get po -n $NAME_SPACE -l $POD_LABEL \
                --field-selector status.phase!=Running -o jsonpath='{.items[*].metadata.name}'`

    if [ -z "$POD_NAME" ];then
      STATUS="ok"
    fi

    echo $STATUS
  register: cert_manager_status
  retries: 50
  delay: 5
  until: "cert_manager_status.stdout_lines[0]=='ok'"