- name: Add an Apt signing key, uses whichever key is at the URL
  become: true
  apt_key:
    url: https://helm.baltorepo.com/organization/signing.asc
    state: present

- name: register apt_repository
  become: true
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: "helm-stable-debian"

- name: install helm3
  become: true
  apt:
    update_cache: yes
    name: helm