- name: apt update & apt upgrade
  become: true
  apt:
    upgrade: safe
    update_cache: yes
    state: latest   

- name: allow port 22 for ssh
  become: true
  ufw:
    rule: allow
    port: "22"

- name: ufw enable
  become: true
  ufw:
    state: enabled    